#!/usr/bin/env node

/**
 * Windows ICO Generation Script
 * Creates icon.ico from PNG sources for manual use
 * Note: electron-builder automatically generates ICO during build
 *
 * Usage: node scripts/generate-ico.js
 */

const fs = require('fs');
const path = require('path');

// Configuration
const SIZES = [16, 32, 48, 64, 128, 256]; // ICO standard sizes
const EXPORT_DIR = path.join(__dirname, '../assets/branding/logo/exports');
const OUTPUT_ICO = path.join(EXPORT_DIR, 'icon.ico');

/**
 * Verify PNG icons and create ICO placeholder
 * electron-builder will auto-generate the actual .ico during build
 */
function generateIco() {
  try {
    console.log(`\n🎨 Verifying PNG icon sources...\n`);
    console.log(`📁 Source directory: ${EXPORT_DIR}\n`);

    // Verify all PNG sources exist
    const missingFiles = [];
    const pngFiles = [];

    for (const size of SIZES) {
      const pngPath = path.join(EXPORT_DIR, `icon-${size}.png`);
      if (!fs.existsSync(pngPath)) {
        missingFiles.push(`icon-${size}.png`);
      } else {
        pngFiles.push(pngPath);
        console.log(`✅ icon-${size}.png (${size}x${size})`);
      }
    }

    if (missingFiles.length > 0) {
      console.error(`\n❌ Missing PNG files:`);
      missingFiles.forEach(file => console.error(`   - ${file}`));
      console.error(`\n⚠️  Run 'npm run generate-icons' first to create PNG files.`);
      process.exit(1);
    }

    // Create a placeholder .ico by copying the 256px PNG
    // The actual multi-resolution ICO will be generated by electron-builder during the build
    const icon256Path = path.join(EXPORT_DIR, 'icon-256.png');
    const iconIcoPath = path.join(EXPORT_DIR, 'icon.ico');

    // For development, we can create icon.ico as a copy of the 256 PNG
    // This allows the file to be referenced, though the real ICO will be built later
    if (!fs.existsSync(iconIcoPath)) {
      fs.copyFileSync(icon256Path, iconIcoPath);
      console.log(`✅ icon.ico (placeholder - electron-builder will generate proper ICO)`);
    } else {
      console.log(`✅ icon.ico (exists)`);
    }

    console.log(`\n✨ PNG icons verified successfully!\n`);
    console.log(`📋 Summary:`);
    console.log(`   ✅ ${pngFiles.length} PNG files ready`);
    console.log(`   ✅ icon.ico created (electron-builder will upgrade during build)\n`);
    console.log(`ℹ️  electron-builder will automatically generate a proper multi-resolution`);
    console.log(`   .ico file during the build process.\n`);

    process.exit(0);

  } catch (error) {
    console.error(`\n❌ Icon verification failed:`, error.message);
    process.exit(1);
  }
}

// Run the generator
generateIco();
