import { app, BrowserWindow, ipcMain, IpcMainInvokeEvent } from 'electron';
// @ts-expect-error: electron-squirrel-startup does not have types
import squirrelStartup from 'electron-squirrel-startup';
import { ProgressData, PythonRequest } from './types';
import { HybridEventBus } from './eventBus';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const SPLASH_WINDOW_WEBPACK_ENTRY: string;
declare const SPLASH_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const eventBus = new HybridEventBus();

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (squirrelStartup) {
  app.quit();
}

// Handle splash screen completion
ipcMain.on('splash-complete', () => {
  console.log('[Main] Splash complete message received');
  showMainWindowAndCloseSplash();
});

ipcMain.handle('python-request', async (event: IpcMainInvokeEvent, request: PythonRequest) => {
  const id = Math.random().toString(36).substring(7);
  const fullRequest = { ...request, id };

  return new Promise((resolve, reject) => {
    // Listen for progress from the bus and forward to renderer
    const progressListener = (data: ProgressData) => {
      event.sender.send(`python-progress-${id}`, data);
    };

    eventBus.on(`progress-${id}`, progressListener);

    eventBus.request(fullRequest).then((response) => {
      eventBus.removeListener(`progress-${id}`, progressListener);
      resolve(response);
    }).catch((error) => {
      eventBus.removeListener(`progress-${id}`, progressListener);
      const errorResponse = {
        id: fullRequest.id,
        error: {
          code: 'IPC_ERROR',
          message: error instanceof Error ? error.message : 'Unknown IPC error',
          timestamp: new Date().toISOString()
        }
      };
      reject(errorResponse);
    });
  });
});

let splashWindow: BrowserWindow | null = null;
let mainWindow: BrowserWindow | null = null;
let backendIsReady = false;

const createSplashWindow = (): void => {
  splashWindow = new BrowserWindow({
    width: 1280,
    height: 900,
    show: true,
    frame: false,
    transparent: true,
    webPreferences: {
      preload: SPLASH_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
      sandbox: true,
      enableRemoteModule: false,
    },
  });

  splashWindow.loadURL(SPLASH_WINDOW_WEBPACK_ENTRY);

  // Handle splash window closed
  splashWindow.on('closed', () => {
    splashWindow = null;
  });
};

const createMainWindow = (): void => {
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    show: false, // Don't show until splash closes
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
      sandbox: true,
      enableRemoteModule: false,
    },
  });

  // Load the index.html of the app
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools
  mainWindow.webContents.openDevTools();

  // Handle main window closed
  mainWindow.on('closed', () => {
    mainWindow = null;
  });
};

const showMainWindowAndCloseSplash = (): void => {
  if (mainWindow) {
    mainWindow.show();
  }
  if (splashWindow) {
    splashWindow.close();
  }
};

const createWindow = (): void => {
  createSplashWindow();
  createMainWindow();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  eventBus.start();
  createWindow();

  eventBus.on('python-log', (data) => {
    BrowserWindow.getAllWindows().forEach(win => {
      win.webContents.send('python-log', data);
    });
  });

  eventBus.on('backend-ready', () => {
    backendIsReady = true;
    
    // Send backend-ready to all windows
    BrowserWindow.getAllWindows().forEach(win => {
      win.webContents.send('backend-ready');
    });

    // If splash is still open, close it and show main window
    if (splashWindow && !splashWindow.isDestroyed()) {
      showMainWindowAndCloseSplash();
    } else if (mainWindow && !mainWindow.isVisible()) {
      // If splash already closed but main window not visible, show it
      mainWindow.show();
    }
  });

  eventBus.on('backend-disconnected', () => {
    BrowserWindow.getAllWindows().forEach(win => {
      win.webContents.send('backend-disconnected');
    });
  });
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  eventBus.stop();
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
